#!/usr/bin/env python3
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# OPSCONFVERSION=0.2.2

import logging
import sys

import opsconf

format = '[%(levelname)s] %(message)s'
logging.basicConfig(format=format)
LOGGER = logging.getLogger('opsconf')

try:
    opsconf.prependFileVersion(sys.argv[1])
except opsconf.OpsconfFatalError as e:
    LOGGER.error(e)
    sys.exit(1)
