#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# OPSCONFVERSION=0.1

if [ -z "${OPSCONF_DIR+x}" ] ; then
    . /usr/share/opsconf/libs/libopsconf
else
    . "$OPSCONF_DIR/libs/libopsconf"
fi

set -e # exit on first error

# Redirect output to stderr.
exec 1>&2

log_debug "githook::post-commit start"
do_push
log_debug "githook::post-commit end"
