#!/usr/bin/env python3
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# OPSCONFVERSION=0.2.0

import logging
import os
import subprocess
import sys

import opsconf


format = '[%(levelname)s] %(message)s'
logging.basicConfig(format=format)
LOGGER = logging.getLogger('opsconf')

if os.path.isfile('.githook/pre-commit'):
    subprocess.run('.githooks/pre-commit')

try:
    opsconf.checkBranchIsWork()
    opsconf.checkBranchUpToDate()
    opsconf.checkCommitUniqueFile()
except opsconf.OpsconfFatalError as e:
    LOGGER.error(e)
    sys.exit(1)
