#!/bin/bash -e

HOOK_SRC=$OPSCONF_DIR/githooks

_show_help() {
    exitcode=$1
    cat <<EOF
opsconf init: initialize (or re-initialize the repository)
EOF
    exit "$exitcode"
}

run_cmd() {
    if [ "$#" -ne 0 ]; then
        subcommand="$1"
        shift
        case "$subcommand" in
            "--help")
                _show_help 0 ;;
            *)
                _show_help 0 ;;
        esac
    fi

    if ! is_git_repo ; then
        git init
        log_info "Git repository initialized: $PWD"
    else
        log_info "I am already in a git repository, moving forwards"
    fi

    GIT_ROOT=$(get_git_root)
    if is_repo_empty ; then
        log_info "Repo is empty, creating branches and first Readme"
        init_branches
    fi

    log_info "Updating hooks" 
    HOOK_DST="${GIT_ROOT}/.git/hooks"
    for hook in "$HOOK_SRC"/* ; do 
    	cp -f "${hook}" "${HOOK_DST}/"
        chmod +x "${HOOK_DST}/$(basename "${hook}")"
    done
    log_info "Hooks updated"
}
