#!/bin/bash -e

_show_help() {
    exitcode=$1
    cat <<EOF
opsconf remove -m REASON FILE: Remove a file.
EOF
    exit "$exitcode"
}

run_cmd() {
    if [ $# -eq 3 ] ; then
        if ! [ "$1" = "-m" ] ; then
            _show_help 1
        fi
        reason="$2"
        file="$3"
    else
        _show_help 1
    fi
    
    echo "Are you sure you want to remove this file (y,N)"
    echo "> $file"
    read -p "" response
    if [ "$response" != y ] && [ "$response" != Y ] ; then
        log_info "Aborting..."
        exit 0
    fi
        
    remove_file "$file" "$reason"
}
