#!/bin/bash -e

_show_help() {
    exitcode=$1
    cat <<EOF
opsconf tag TAG: tag the current state of the repository with tag TAG.
EOF
    exit "$exitcode"
}

run_cmd() {
    if [ "$#" -eq 1 ] ; then
        if [ "$1" = "--help" ] ; then
            _show_help 0
        else
            tag=$1
        fi
    else
        _show_help 1
    fi

    git_tag "$tag"
    git push origin "$tag"
}
