#!/bin/bash -e

_show_help() {
    exitcode=$1
    cat <<EOF
opsconf diff FILE VERSION_OLD VERSION_NEW: Show the difference of FILE between version VERSION_OLD and VERSION_NEW
EOF
    exit "$exitcode"
}

run_cmd() {
    if [ $# -eq 3 ]; then
        file="$1"
        v1="$2"
        v2="$3"  # TODO: v3 is optional => HEAD
    else
        _show_help 1
    fi

    diff_between_versions "$file" "$v1" "$v2"
}
