#!/bin/bash -e

_show_help() {
    exitcode=$1
    cat <<EOF
opsconf validate FILE VERSION: Set the version VERSION of the file FILE as valid.
EOF
    exit "$exitcode"
}

case_branch_work() {
    target_branch="$1"
    file="$2"
    cmd="$3"
    version="$4"

    current_path="$(pwd)"
    current_branch="$OPSCONF_BRANCH_WORK"
    log_debug "We are in branch $current_branch"
    file_path="$current_path/$file"
    file_path="${file_path/$(git_get_root)\//}"
    cd "$(git_get_root)" &> /dev/null
    opsconf checkout "${target_branch}" > /dev/null
    log_debug "We changed to branch ${target_branch}"
    log_debug "Let's re-run 'opsconf $cmd'"
    if ! opsconf "$cmd" "$file_path" "$version" ; then
        return_with_error="yes"
    fi
    opsconf checkout "$current_branch" > /dev/null
    log_debug "We are back in branch $OPSCONF_BRANCH_WORK"
    cd "$current_path" &> /dev/null
    if [ ! -z "${return_with_error}" ] ; then
        exit 1
    fi
}

run_cmd() {
    if [ $# -eq 2 ] ; then
        file=$1
        version=$2
    else
        _show_help 1
    fi

    if is_current_branch_work ; then
        case_branch_work "$OPSCONF_BRANCH_VALID" "$file" "validate" "$version"
    elif is_current_branch_valid ; then
        retrieve_version "$OPSCONF_BRANCH_WORK" "$file" "$version"
    else
        log_error "Validating a file can only be done on the \"$OPSCONF_BRANCH_VALID\" branch. Aborting."
        exit 1
    fi
}
