---
include:
  - project: 'DNO-OP/ci-resources'
    ref: master
    file: 'check_code_quality.yml'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - test

test-job:
  stage: test
  tags:
    - Usine_Logicielle_Podman
  image: artifactory.cnes.fr/laprod-images-docker/redhat/ubi8
  script:
    - rm /etc/yum.repos.d/ubi.repo
    - yum install -y python36 pylint ShellCheck git diffutils > /dev/null
    - tests/run_tests.sh

