#!/bin/bash

git_is_git() {
    git rev-parse --verify HEAD >/dev/null 2>&1
    # git rev-parse --is-inside-work-tree
}

git_get_root() {
    git rev-parse --show-toplevel
}

git_get_gitdir() {
    git rev-parse --git-dir
}

git_current_branch() {
    git rev-parse --abbrev-ref HEAD
}

git_exist_branch() {
    branch=$1
    git show-ref --quiet "refs/heads/$branch"
}

git_checkout() {
    rev=$1
    git checkout "$rev"
}

git_create_branch() {
    branch=$1
    git checkout -b "$branch"
}

git_create_branch_orphan() {
    branch=$1
    git checkout --orphan "$branch"
}

git_add() {
    git add "$@"
}
