#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# OPSCONFVERSION=0.1

. /usr/share/include/libopsconf

# Redirect output to stderr.
exec 1>&2

forbid_several_files_commit
