#!/bin/bash

function _show_help() {
    exitcode=$1
    cat <<EOF
opsconf rollback -m reason FILE PREVIOUS_VERSION: Create a new version of FILE with the content of the version PREVIOUS_VERSION
EOF
    exit $exitcode
}

function main() {
    
    rollback_to_version $file $version $reason
}

main $@