name: tests
on: 
  pull_request:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.pylintrc'

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install dependendencies
        run: sudo apt install -y shellcheck
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'
          cache: 'pip'
      - run: pip install coverage pylint
      - run: ./tests/run_tests.sh
    
  
